image: Visual Studio 2019

# build: off

before_build:
  - ps: C:\python39\python.exe -m pip install --upgrade pip --no-warn-script-location
  - ps: C:\Python39\Scripts\pip.exe install selenium --no-warn-script-location
  - ps: C:\python39\python.exe .\Entry-2020-12-16.py

on_finish:
  - ps: $blockRdp = $true;
  - ps: .\enable-rdp.ps1
