image: Visual Studio 2019

# build: off

before_build:
  - ps: C:\Python39\Script\pip.exe install selenium 
  - ps: C:\python39\python.exe .\Entry-2020-12-16.py

on_finish:
  - ps: $blockRdp = $true;
  - ps: .\enable-rdp.ps1
